# Site settings
title: "I Am MattD"
url: "//iammattd.github.io"
paginate: 5
author:
    name: MattD
    github: IAmMattD
    email: 1289367510@qq.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
kramdown:
    input: GFM
permalink: /:year/:month/:date/:title.html
gems: [jekyll-paginate]
exclude: [Gemfile, Gemfile.lock, qrsync, Rakefile]
assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: mattd
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# tinysou.com
search:
    tinysou:
        engineKey: 

# 网站统计
analytics:
    baidu:
        siteid:                             # 百度统计 js 代码后的字符串
webmaster:
    baidu:
        verify:
    google:
        verify:
    bing:
        verify:
